In [7]:
import sys
sys.path.append('..')

from src.data.fetch_openaq import run_full_coverage_audit
from src.config import CITIES, RAW_OPENAQ_DIR
import pandas as pd

In [8]:
audit_df = run_full_coverage_audit()

Fetching all Indonesia locations from OpenAQ v3...
Total Indonesia locations retrieved: 39
Auditing jakarta...
Auditing surabaya...
[WARNING] No locations found near Surabaya
Auditing bandung...
Auditing medan...

Coverage audit saved to: C:\AQSEL\me\KARIR\Portofolio Setelah Wisuda\EDA Project Indonesia Urban Air Quality Analysis\data\raw\openaq\coverage_audit.csv

Summary by city:
          total  pm25_stations  pm10_stations  monitors
city_key
bandung       2              2              1         1
jakarta      26             22              7         7
medan         1              1              0         0

In [9]:
print(f"Total stations found: {len(audit_df)}")
print(f"\nCities covered: {audit_df['city'].unique()}")
print(f"\nDetailed view:")
audit_df[['city', 'name', 'is_monitor', 'has_pm25', 'has_pm10',
          'first_updated', 'last_updated']].sort_values('city')

Total stations found: 29

Cities covered: <ArrowStringArray>
['Jakarta', 'Bandung', 'Medan']
Length: 3, dtype: str

Detailed view:

,city,name,is_monitor,has_pm25,has_pm10,first_updated,last_updated
26,Bandung,SPARTAN - ITB Bandung,True,True,False,2016-08-01T17:00:00Z,2018-01-29T10:00:00Z
27,Bandung,Pasteur Gateway Apartment,False,True,True,2024-09-10T08:00:00Z,2024-11-04T01:00:00Z
0,Jakarta,US Diplomatic Post: Jakarta South,True,True,False,2016-01-30T01:00:00Z,2016-11-09T16:00:00Z
1,Jakarta,US Diplomatic Post: Jakarta Central,True,True,False,2016-01-30T01:00:00Z,2016-11-09T16:00:00Z
2,Jakarta,Jakarta South,True,True,False,2022-10-03T20:00:00Z,2025-11-04T21:00:00Z
3,Jakarta,Jakarta Central,True,True,False,2016-11-09T18:00:00Z,2025-04-09T14:00:00Z
4,Jakarta,Cilandek,False,True,False,NaN,NaN
5,Jakarta,Cilandek,False,True,False,NaN,NaN
6,Jakarta,Depok,False,True,True,2023-08-01T07:00:00Z,2025-12-20T07:00:00Z
7,Jakarta,Cipete,False,True,False,NaN,NaN
8,Jakarta,Qoryah Darussalam,False,True,True,2023-09-12T10:00:00Z,2025-10-17T17:00:00Z
9,Jakarta,Jihan Fauziah Hamdi,False,True,True,2023-10-30T13:00:00Z,2024-05-26T00:00:00Z
10,Jakarta,Jakarta,False,True,True,2024-01-25T08:36:19Z,2026-05-20T01:03:57Z
11,Jakarta,Krukut,False,True,True,2024-01-09T08:00:00Z,2024-09-10T08:00:00Z
12,Jakarta,Margonda Residence 3,False,True,True,2024-05-16T10:00:00Z,2024-09-04T05:00:00Z
13,Jakarta,Jaja,False,True,True,2024-09-29T11:00:00Z,2024-10-01T09:00:00Z
14,Jakarta,Cipete Jakarta,False,True,False,NaN,NaN
15,Jakarta,Cipete Jakarta,False,True,False,NaN,NaN
16,Jakarta,Cipete Dec,False,True,False,NaN,NaN
17,Jakarta,Bogor Selatan,False,True,False,2025-08-29T08:00:00Z,2026-03-02T05:00:00Z
18,Jakarta,West Jakarta Mayor Office,True,True,False,2023-09-30T17:00:00Z,2025-06-30T16:00:00Z
19,Jakarta,East Jakarta Mayor Office,True,True,False,2023-09-30T17:00:00Z,2025-06-30T16:00:00Z
20,Jakarta,Rusunawa Marunda,True,True,False,2023-09-30T17:00:00Z,2025-06-30T16:00:00Z
21,Jakarta,North Jakarta,False,False,False,NaN,NaN
22,Jakarta,South Jakarta,False,False,False,NaN,NaN
23,Jakarta,East Jakarta,False,False,False,NaN,NaN
24,Jakarta,West Jakarta,False,False,False,NaN,NaN
25,Jakarta,D'Mall Depok,False,True,False,2025-10-14T23:00:00Z,2025-11-22T14:00:00Z
28,Medan,USU,False,True,False,2025-10-10T09:00:00Z,2026-05-19T14:00:00Z

In [10]:
pm25_stations = audit_df[audit_df['has_pm25'] == True]
print(f"Stations with PM2.5: {len(pm25_stations)}")
pm25_stations[['city', 'name', 'is_monitor', 'first_updated', 'last_updated']]

Stations with PM2.5: 25

,city,name,is_monitor,first_updated,last_updated
0,Jakarta,US Diplomatic Post: Jakarta South,True,2016-01-30T01:00:00Z,2016-11-09T16:00:00Z
1,Jakarta,US Diplomatic Post: Jakarta Central,True,2016-01-30T01:00:00Z,2016-11-09T16:00:00Z
2,Jakarta,Jakarta South,True,2022-10-03T20:00:00Z,2025-11-04T21:00:00Z
3,Jakarta,Jakarta Central,True,2016-11-09T18:00:00Z,2025-04-09T14:00:00Z
4,Jakarta,Cilandek,False,NaN,NaN
5,Jakarta,Cilandek,False,NaN,NaN
6,Jakarta,Depok,False,2023-08-01T07:00:00Z,2025-12-20T07:00:00Z
7,Jakarta,Cipete,False,NaN,NaN
8,Jakarta,Qoryah Darussalam,False,2023-09-12T10:00:00Z,2025-10-17T17:00:00Z
9,Jakarta,Jihan Fauziah Hamdi,False,2023-10-30T13:00:00Z,2024-05-26T00:00:00Z
10,Jakarta,Jakarta,False,2024-01-25T08:36:19Z,2026-05-20T01:03:57Z
11,Jakarta,Krukut,False,2024-01-09T08:00:00Z,2024-09-10T08:00:00Z
12,Jakarta,Margonda Residence 3,False,2024-05-16T10:00:00Z,2024-09-04T05:00:00Z
13,Jakarta,Jaja,False,2024-09-29T11:00:00Z,2024-10-01T09:00:00Z
14,Jakarta,Cipete Jakarta,False,NaN,NaN
15,Jakarta,Cipete Jakarta,False,NaN,NaN
16,Jakarta,Cipete Dec,False,NaN,NaN
17,Jakarta,Bogor Selatan,False,2025-08-29T08:00:00Z,2026-03-02T05:00:00Z
18,Jakarta,West Jakarta Mayor Office,True,2023-09-30T17:00:00Z,2025-06-30T16:00:00Z
19,Jakarta,East Jakarta Mayor Office,True,2023-09-30T17:00:00Z,2025-06-30T16:00:00Z
20,Jakarta,Rusunawa Marunda,True,2023-09-30T17:00:00Z,2025-06-30T16:00:00Z
25,Jakarta,D'Mall Depok,False,2025-10-14T23:00:00Z,2025-11-22T14:00:00Z
26,Bandung,SPARTAN - ITB Bandung,True,2016-08-01T17:00:00Z,2018-01-29T10:00:00Z
27,Bandung,Pasteur Gateway Apartment,False,2024-09-10T08:00:00Z,2024-11-04T01:00:00Z
28,Medan,USU,False,2025-10-10T09:00:00Z,2026-05-19T14:00:00Z